remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 

title: 駭遠傳給的 RTL6100W
description: 駭遠傳給的 RTL6100W
encoding: utf-8

exclude: ["README.md", "LICENSE", "*.gem", "*.gemspec", "Gemfile.lock"]